# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.transformation import (
    filter_by_geometry_type as filter_by_geometry_type,
)

get_patrols_from_combined_params = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrols_from_combined_params",  # 🧪
)  # 🧪

get_patrol_observations_from_patrols_df_and_combined_params = (
    create_func_magicmock(  # 🧪
        anchor="ecoscope.platform.tasks.io",  # 🧪
        func_name="get_patrol_observations_from_patrols_df_and_combined_params",  # 🧪
    )
)  # 🧪
from ecoscope.platform.tasks.analysis import create_meshgrid as create_meshgrid
from ecoscope.platform.tasks.config import get_bounding_box as get_bounding_box
from ecoscope.platform.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope.platform.tasks.config import get_segment_filter as get_segment_filter
from ecoscope.platform.tasks.config import set_traj_filters as set_traj_filters
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)

from occupancy_model_tasks.tasks import (
    count_events_and_effort as count_events_and_effort,
)
from occupancy_model_tasks.tasks import (
    missing_trajectories_or_grid as missing_trajectories_or_grid,
)
from occupancy_model_tasks.tasks import (
    set_distance_covariates as set_distance_covariates,
)
from occupancy_model_tasks.tasks import set_gee_covariates as set_gee_covariates

label_grid_with_gee_covariates = create_func_magicmock(  # 🧪
    anchor="occupancy_model_tasks.tasks",  # 🧪
    func_name="label_grid_with_gee_covariates",  # 🧪
)  # 🧪

label_grid_with_distance_covariates = create_func_magicmock(  # 🧪
    anchor="occupancy_model_tasks.tasks",  # 🧪
    func_name="label_grid_with_distance_covariates",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.io import (
    persist_grouped_dfs_for_results_download as persist_grouped_dfs_for_results_download,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    drop_nan_values_by_column as drop_nan_values_by_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import sort_values as sort_values

from occupancy_model_tasks.tasks import (
    all_dependencies_skipped as all_dependencies_skipped,
)
from occupancy_model_tasks.tasks import build_occupancy_design as build_occupancy_design
from occupancy_model_tasks.tasks import (
    check_target_event_types as check_target_event_types,
)
from occupancy_model_tasks.tasks import (
    classify_occupancy_zones as classify_occupancy_zones,
)
from occupancy_model_tasks.tasks import draw_coefficient_plot as draw_coefficient_plot
from occupancy_model_tasks.tasks import extract_fit_metric as extract_fit_metric
from occupancy_model_tasks.tasks import fit_occupancy_glm as fit_occupancy_glm
from occupancy_model_tasks.tasks import (
    get_occupancy_fit_summary as get_occupancy_fit_summary,
)
from occupancy_model_tasks.tasks import get_posterior_draws as get_posterior_draws
from occupancy_model_tasks.tasks import (
    predict_occupancy_surface as predict_occupancy_surface,
)
from occupancy_model_tasks.tasks import (
    summarize_occupancy_run as summarize_occupancy_run,
)
from occupancy_model_tasks.tasks import write_grid_cog as write_grid_cog


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    gee_client_name = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=None, **(params.get("groupers") or {}))
        .call()
    )

    study_area = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("study_area")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client_name, **(params.get("study_area") or {}))
        .call()
    )

    study_area_polygons = (
        task(filter_by_geometry_type)
        .validate()
        .set_task_instance_id("study_area_polygons")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=study_area,
            geometry_types=["Polygon", "MultiPolygon"],
            **(params.get("study_area_polygons") or {}),
        )
        .call()
    )

    er_patrol_and_events_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_states=None,
            include_patrol_details=True,
            raise_on_empty=False,
            include_null_geometry=False,
            truncate_to_time_range=True,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            **(params.get("er_patrol_and_events_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_and_events_params,
            **(params.get("prefetch_patrols") or {}),
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    convert_patrols_to_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_to_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_patrols_to_tz") or {}),
        )
        .call()
    )

    convert_events_to_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_to_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_to_tz") or {}),
        )
        .call()
    )

    patrol_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("patrol_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    drop_extra_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_to_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_obs") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_obs,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("patrol_traj") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    filter_patrol_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_tz,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            **(params.get("filter_patrol_events") or {}),
        )
        .call()
    )

    pe_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("pe_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_patrol_events,
            time_col="time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("pe_add_temporal_index") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            groupers=groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    split_pe_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_pe_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_add_temporal_index,
            groupers=groupers,
            **(params.get("split_pe_groups") or {}),
        )
        .call()
    )

    meshgrid = (
        task(create_meshgrid)
        .validate()
        .set_task_instance_id("meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=study_area_polygons,
            crs="EPSG:3857",
            intersecting_only=True,
            **(params.get("meshgrid") or {}),
        )
        .call()
    )

    effort_grid = (
        task(count_events_and_effort)
        .validate()
        .set_task_instance_id("effort_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                missing_trajectories_or_grid,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=meshgrid,
            events=filter_patrol_events,
            **(params.get("effort_grid") or {}),
        )
        .mapvalues(argnames=["trajectories"], argvalues=split_traj_groups)
    )

    gee_covariates = (
        task(set_gee_covariates)
        .validate()
        .set_task_instance_id("gee_covariates")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_covariates") or {}))
        .call()
    )

    distance_covariates = (
        task(set_distance_covariates)
        .validate()
        .set_task_instance_id("distance_covariates")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("distance_covariates") or {}))
        .call()
    )

    gee_labels = (
        task(label_grid_with_gee_covariates)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("gee_labels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client_name,
            grid=meshgrid,
            covariates=gee_covariates,
            time_range=time_range,
            df_chunk_size=2000,
            **(params.get("gee_labels") or {}),
        )
        .call()
    )

    distance_labels = (
        task(label_grid_with_distance_covariates)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("distance_labels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            grid=meshgrid,
            covariates=distance_covariates,
            **(params.get("distance_labels") or {}),
        )
        .call()
    )

    occupancy_design = (
        task(build_occupancy_design)
        .validate()
        .set_task_instance_id("occupancy_design")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            covariate_frames=[gee_labels, distance_labels],
            **(params.get("occupancy_design") or {}),
        )
        .mapvalues(argnames=["cells"], argvalues=effort_grid)
    )

    occupancy_fit = (
        task(fit_occupancy_glm)
        .validate()
        .set_task_instance_id("occupancy_fit")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gee_covariates=gee_covariates,
            distance_covariates=distance_covariates,
            **(params.get("occupancy_fit") or {}),
        )
        .mapvalues(argnames=["design"], argvalues=occupancy_design)
    )

    zipped_fit_design = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zipped_fit_design")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                all_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[occupancy_fit, occupancy_design],
            **(params.get("zipped_fit_design") or {}),
        )
        .call()
    )

    predicted = (
        task(predict_occupancy_surface)
        .validate()
        .set_task_instance_id("predicted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(n_draws=500, **(params.get("predicted") or {}))
        .mapvalues(argnames=["fit", "design"], argvalues=zipped_fit_design)
    )

    occupancy_zones = (
        task(classify_occupancy_zones)
        .validate()
        .set_task_instance_id("occupancy_zones")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            boundary=study_area_polygons,
            value_column="p_mean",
            class_method="tertiles",
            filename_prefix="occupancy_zones",
            **(params.get("occupancy_zones") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=predicted)
    )

    cog_mean = (
        task(write_grid_cog)
        .validate()
        .set_task_instance_id("cog_mean")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value_column="p_mean",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="occupancy_mean",
            nodata=-9999,
            **(params.get("cog_mean") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=predicted)
    )

    cog_sd = (
        task(write_grid_cog)
        .validate()
        .set_task_instance_id("cog_sd")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value_column="p_sd",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="occupancy_sd",
            nodata=-9999,
            **(params.get("cog_sd") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=predicted)
    )

    persist_cells = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_cells")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=predicted,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["geoparquet"],
            filename_prefix="occupancy_cells",
            sanitize=True,
            **(params.get("persist_cells") or {}),
        )
        .call()
    )

    persist_zones = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_zones")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=occupancy_zones,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["geoparquet"],
            filename_prefix="occupancy_zones",
            sanitize=True,
            **(params.get("persist_zones") or {}),
        )
        .call()
    )

    posterior_draws = (
        task(get_posterior_draws)
        .validate()
        .set_task_instance_id("posterior_draws")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("posterior_draws") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    persist_posterior_draws = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_posterior_draws")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=posterior_draws,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["csv"],
            filename_prefix="posterior_draws",
            sanitize=False,
            **(params.get("persist_posterior_draws") or {}),
        )
        .call()
    )

    fit_summary = (
        task(get_occupancy_fit_summary)
        .validate()
        .set_task_instance_id("fit_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("fit_summary") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    persist_coefficients = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_coefficients")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=fit_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["csv"],
            filename_prefix="coefficients",
            sanitize=False,
            **(params.get("persist_coefficients") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    event_type_check = (
        task(check_target_event_types)
        .validate()
        .set_task_instance_id("event_type_check")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_and_events_params,
            patrols_df=prefetch_patrols,
            **(params.get("event_type_check") or {}),
        )
        .call()
    )

    run_summary = (
        task(summarize_occupancy_run)
        .validate()
        .set_task_instance_id("run_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(event_type_check=event_type_check, **(params.get("run_summary") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    summary_widgets = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("summary_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Model Summary", **(params.get("summary_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=run_summary)
    )

    summary_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("summary_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=summary_widgets, **(params.get("summary_widget") or {}))
        .call()
    )

    stat_events_value = (
        task(extract_fit_metric)
        .validate()
        .set_task_instance_id("stat_events_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(metric="n_events", **(params.get("stat_events_value") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    stat_events_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("stat_events_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Target Events",
            decimal_places=0,
            **(params.get("stat_events_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=stat_events_value)
    )

    stat_events_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("stat_events_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=stat_events_widgets, **(params.get("stat_events_widget") or {})
        )
        .call()
    )

    stat_surveyed_value = (
        task(extract_fit_metric)
        .validate()
        .set_task_instance_id("stat_surveyed_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(metric="n_surveyed", **(params.get("stat_surveyed_value") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    stat_surveyed_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("stat_surveyed_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Surveyed Cells",
            decimal_places=0,
            **(params.get("stat_surveyed_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=stat_surveyed_value)
    )

    stat_surveyed_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("stat_surveyed_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=stat_surveyed_widgets, **(params.get("stat_surveyed_widget") or {})
        )
        .call()
    )

    stat_presence_value = (
        task(extract_fit_metric)
        .validate()
        .set_task_instance_id("stat_presence_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(metric="n_presence", **(params.get("stat_presence_value") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    stat_presence_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("stat_presence_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Cells with Target Events",
            decimal_places=0,
            **(params.get("stat_presence_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=stat_presence_value)
    )

    stat_presence_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("stat_presence_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=stat_presence_widgets, **(params.get("stat_presence_widget") or {})
        )
        .call()
    )

    stat_auc_value = (
        task(extract_fit_metric)
        .validate()
        .set_task_instance_id("stat_auc_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(metric="auc", **(params.get("stat_auc_value") or {}))
        .mapvalues(argnames=["fit"], argvalues=occupancy_fit)
    )

    stat_auc_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("stat_auc_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Holdout AUC",
            decimal_places=2,
            **(params.get("stat_auc_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=stat_auc_value)
    )

    stat_auc_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("stat_auc_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=stat_auc_widgets, **(params.get("stat_auc_widget") or {}))
        .call()
    )

    occ_cells = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("occ_cells")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="p_mean", **(params.get("occ_cells") or {}))
        .mapvalues(argnames=["df"], argvalues=predicted)
    )

    occ_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("occ_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="p_mean",
            ascending=True,
            na_position="last",
            **(params.get("occ_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=occ_cells)
    )

    occ_classified = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("occ_classified")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="p_mean",
            output_column_name="p_mean_bins",
            classification_options={"scheme": "equal_interval", "k": 8},
            label_options={"label_ranges": True, "label_decimals": 2},
            **(params.get("occ_classified") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=occ_sorted)
    )

    occ_colored = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("occ_colored")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="p_mean_bins",
            output_column_name="p_mean_colormap",
            colormap=[
                "#f4db20",
                "#ffb700",
                "#ed3ea2",
                "#a100cb",
                "#5c4fe7",
                "#0056c7",
                "#00882e",
                "#78d811",
            ],
            **(params.get("occ_colored") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=occ_classified)
    )

    occ_renamed = (
        task(map_columns)
        .validate()
        .set_task_instance_id("occ_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "p_mean": "Probability",
                "p_sd": "Uncertainty (SD)",
                "effort_km": "Patrol Effort (km)",
                "event_count": "Target Events",
            },
            raise_if_not_found=False,
            duplicate_strategy="suffix",
            **(params.get("occ_renamed") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=occ_colored)
    )

    occ_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("occ_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "p_mean_colormap",
                "get_line_width": 0,
                "opacity": 0.6,
            },
            legend={"label_column": "p_mean_bins", "color_column": "p_mean_colormap"},
            tooltip_columns=[
                "Probability",
                "Uncertainty (SD)",
                "Patrol Effort (km)",
                "Target Events",
            ],
            **(params.get("occ_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=occ_renamed)
    )

    events_colored = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("events_colored")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="event_type",
            output_column_name="event_colormap",
            colormap=["#3e35a3"],
            **(params.get("events_colored") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_pe_groups)
    )

    events_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("events_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_radius": 4,
                "radius_units": "pixels",
                "fill_color_column": "event_colormap",
                "opacity": 1,
                "pickable": True,
            },
            legend={"label_column": "event_type", "color_column": "event_colormap"},
            tooltip_columns=["event_type", "time", "patrol_serial_number"],
            **(params.get("events_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=events_colored)
    )

    occ_map_layers = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("occ_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                all_dependencies_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[occ_layer, events_layer], **(params.get("occ_map_layers") or {})
        )
        .call()
    )

    occ_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("occ_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Probability",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            **(params.get("occ_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=occ_map_layers)
    )

    occ_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("occ_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="occupancy_map",
            **(params.get("occ_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=occ_ecomap)
    )

    occ_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("occ_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Occupancy Probability", **(params.get("occ_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=occ_ecomap_html)
    )

    occ_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("occ_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=occ_map_widgets, **(params.get("occ_map_widget") or {}))
        .call()
    )

    zone_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("zone_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="zone_class",
            ascending=True,
            na_position="last",
            **(params.get("zone_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=occupancy_zones)
    )

    zone_colored = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("zone_colored")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="zone_label",
            output_column_name="zone_colormap",
            colormap=["#f4db20", "#ffb700", "#ed3ea2"],
            **(params.get("zone_colored") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=zone_sorted)
    )

    zone_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("zone_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "zone_colormap",
                "get_line_width": 1,
                "opacity": 0.6,
            },
            legend={"label_column": "zone_label", "color_column": "zone_colormap"},
            tooltip_columns=["zone_label", "name", "area_km2"],
            **(params.get("zone_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=zone_colored)
    )

    zone_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("zone_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Occupancy Zone",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            **(params.get("zone_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=zone_layer)
    )

    zone_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("zone_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="occupancy_zone_map",
            **(params.get("zone_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=zone_ecomap)
    )

    zone_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("zone_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Occupancy Zones", **(params.get("zone_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=zone_ecomap_html)
    )

    zone_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("zone_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=zone_map_widgets, **(params.get("zone_map_widget") or {}))
        .call()
    )

    sd_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sd_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="p_sd",
            ascending=True,
            na_position="last",
            **(params.get("sd_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=occ_cells)
    )

    sd_classified = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("sd_classified")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="p_sd",
            output_column_name="p_sd_bins",
            classification_options={"scheme": "equal_interval", "k": 8},
            label_options={"label_ranges": True, "label_decimals": 3},
            **(params.get("sd_classified") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sd_sorted)
    )

    sd_colored = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("sd_colored")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="p_sd_bins",
            output_column_name="p_sd_colormap",
            colormap=[
                "#f4db20",
                "#ffb700",
                "#ed3ea2",
                "#a100cb",
                "#5c4fe7",
                "#0056c7",
                "#00882e",
                "#78d811",
            ],
            **(params.get("sd_colored") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sd_classified)
    )

    sd_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("sd_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "p_sd_colormap",
                "get_line_width": 0,
                "opacity": 0.6,
            },
            legend={"label_column": "p_sd_bins", "color_column": "p_sd_colormap"},
            tooltip_columns=["p_sd", "p_mean"],
            **(params.get("sd_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=sd_colored)
    )

    sd_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("sd_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Uncertainty (SD)",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            **(params.get("sd_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=sd_layer)
    )

    sd_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("sd_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="uncertainty_map",
            **(params.get("sd_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=sd_ecomap)
    )

    sd_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("sd_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Prediction Uncertainty", **(params.get("sd_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=sd_ecomap_html)
    )

    sd_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("sd_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=sd_map_widgets, **(params.get("sd_map_widget") or {}))
        .call()
    )

    survey_cells = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("survey_cells")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="surveyed_y", **(params.get("survey_cells") or {}))
        .mapvalues(argnames=["df"], argvalues=occupancy_design)
    )

    survey_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("survey_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="survey_status",
            ascending=False,
            na_position="last",
            **(params.get("survey_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=survey_cells)
    )

    survey_colored = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("survey_colored")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="survey_status",
            output_column_name="survey_colormap",
            colormap=["#3e35a3", "#488a00"],
            **(params.get("survey_colored") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=survey_sorted)
    )

    survey_renamed = (
        task(map_columns)
        .validate()
        .set_task_instance_id("survey_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "survey_status": "Survey Status",
                "effort_km": "Patrol Effort (km)",
                "event_count": "Target Events",
            },
            raise_if_not_found=False,
            duplicate_strategy="suffix",
            **(params.get("survey_renamed") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=survey_colored)
    )

    survey_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("survey_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "survey_colormap",
                "get_line_width": 0,
                "opacity": 0.6,
            },
            legend={"label_column": "Survey Status", "color_column": "survey_colormap"},
            tooltip_columns=["Survey Status", "Patrol Effort (km)", "Target Events"],
            **(params.get("survey_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=survey_renamed)
    )

    survey_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("survey_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Survey Status",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            **(params.get("survey_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=survey_layer)
    )

    survey_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("survey_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="survey_map",
            **(params.get("survey_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=survey_ecomap)
    )

    survey_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("survey_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Surveyed Cells", **(params.get("survey_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=survey_ecomap_html)
    )

    survey_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("survey_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=survey_map_widgets, **(params.get("survey_map_widget") or {}))
        .call()
    )

    coef_plot = (
        task(draw_coefficient_plot)
        .validate()
        .set_task_instance_id("coef_plot")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(title="", **(params.get("coef_plot") or {}))
        .mapvalues(argnames=["summary"], argvalues=fit_summary)
    )

    coef_plot_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("coef_plot_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="coefficient_plot",
            **(params.get("coef_plot_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=coef_plot)
    )

    coef_plot_widgets = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("coef_plot_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Covariate Effects", **(params.get("coef_plot_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=coef_plot_html)
    )

    coef_plot_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("coef_plot_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=coef_plot_widgets, **(params.get("coef_plot_widget") or {}))
        .call()
    )

    coef_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("coef_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("coef_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=fit_summary)
    )

    coef_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("coef_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="coefficient_table",
            **(params.get("coef_table_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=coef_table)
    )

    coef_table_widgets = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("coef_table_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Coefficients (standardised)",
            **(params.get("coef_table_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=coef_table_html)
    )

    coef_table_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("coef_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=coef_table_widgets, **(params.get("coef_table_widget") or {}))
        .call()
    )

    occupancy_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("occupancy_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                summary_widget,
                stat_events_widget,
                stat_surveyed_widget,
                stat_presence_widget,
                stat_auc_widget,
                occ_map_widget,
                zone_map_widget,
                sd_map_widget,
                survey_map_widget,
                coef_plot_widget,
                coef_table_widget,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("occupancy_dashboard") or {}),
        )
        .call()
    )

    return occupancy_dashboard
